# Generated by Django 4.2.11 on 2024-05-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbankrupt',
            name='bankrupt',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
